# Generated by Django 6.0.6 on 2026-06-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('upload', 'Upload Document'), ('download', 'Download Document'), ('edit', 'Edit Document'), ('delete', 'Delete Document'), ('approve', 'Approve Document'), ('reject', 'Reject Document'), ('view', 'View Document'), ('share', 'Share Document'), ('register', 'Register Account')], max_length=50),
        ),
    ]
