# Generated by Django 5.2.15 on 2026-06-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
